language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t xinboxia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xinboxia/docker-react npm run test

region: us-west-1

app: docker-web

env: DockerWeb-env

bucket_name: elasticbeanstalk-us-west-1-762283273395

bucket_path: docker

access_key_id: AKIA3C647VSZUHJZO27M

secret_access_key: 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

