language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t xinboxia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xinboxia/docker-react npm run test

deploy: 
  region: us-west-1
  app: docker-web
  env: DockerWeb-env
  bucket_name: elasticbeanstalk-us-west-1-762283273395
  bucket_path: docker
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on: 
    branch: master


